[[constraint]]
  name = "github.com/gorilla/handlers"
  version = "1.4.0"

[[constraint]]
  name = "github.com/gorilla/mux"
  version = "1.6.2-22-ga796238"

[prune]
  go-tests = true
  unused-packages = true
